import './modules/model/blueprint.test.js';
import './modules/model/materials.test.js';
import './modules/model/nbt.test.js';
import './modules/model/snbt.test.js';
import './modules/model/structure.test.js';
import './modules/model/tools.test.js';
import './modules/view/assets.test.js';
import './modules/view/html.test.js';
import './modules/view/render.test.js';
